# Generated by Django 5.1.7 on 2025-03-07 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vydaje', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypVydaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('spz', models.CharField(max_length=20, unique=True)),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vydaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('castka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('popis', models.TextField(blank=True, null=True)),
                ('tachometr', models.IntegerField(blank=True, null=True)),
                ('mnozstvi_litru', models.FloatField(blank=True, null=True)),
                ('cena_za_litr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vydaje.auto')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vydaje.typvydaje')),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
