# Generated by Django 5.1.11 on 2025-08-16 15:45

from django.db import migrations


def create_default_types(apps, schema_editor):
    TypVydaje = apps.get_model("vydaje", "TypVydaje")
    default_types = [
        "Benzin",
        "Servis",
        "Pojištění",
        "Oprava",
        "Dálniční známka",
        "Parkování",
    ]
    for name in default_types:
        TypVydaje.objects.get_or_create(nazev=name)


def remove_default_types(apps, schema_editor):
    TypVydaje = apps.get_model("vydaje", "TypVydaje")
    default_types = [
        "Benzin",
        "Servis",
        "Pojištění",
        "Oprava",
        "Dálniční známka",
        "Parkování",
    ]
    TypVydaje.objects.filter(nazev__in=default_types).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("vydaje", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_types, remove_default_types),
    ]
