# Generated by Django 5.1.11 on 2025-08-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vydaje", "0003_default_typy"),
    ]

    operations = [
        migrations.AddField(
            model_name="vydaj",
            name="datum_pridani",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
