# Generated by Django 5.1.11 on 2025-08-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vydaje", "0004_vydaj_datum_pridani"),
    ]

    operations = [
        migrations.AddField(
            model_name="vydaj",
            name="najezd_od_posledniho_tankovani",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
