# Generated by Django 5.1.11 on 2025-08-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vydaje", "0005_vydaj_najezd_od_posledniho_tankovani"),
    ]

    operations = [
        migrations.AddField(
            model_name="auto",
            name="den_splatnosti",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auto",
            name="mesicni_platba",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="auto",
            name="operativni_leasing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="auto",
            name="porizovaci_naklad",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="auto",
            name="posledni_platba",
            field=models.DateField(blank=True, null=True),
        ),
    ]
