# Generated by Django 5.1.11 on 2025-08-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vydaje", "0006_auto_den_splatnosti_auto_mesicni_platba_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vydaj",
            name="najezd_od_posledniho_tankovani",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
