# Generated by Django 5.1.11 on 2025-08-19 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vydaje", "0007_alter_vydaj_najezd_od_posledniho_tankovani"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auto",
            name="uzivatel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auta",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vydaj",
            name="uzivatel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vydaje",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
