from django.urls import path
from .views import (
    home,
    landing,
    odhlaseni,
    export_vydaje_csv,
    prihlaseni,
    registrace,
    auto_detail,
    VydajListView,
    VydajCreateView,
    VydajUpdateView,
    VydajDeleteView,
    AutoListView,
    AutoCreateView,
    AutoUpdateView,
    AutoDeleteView,
    TypVydajeListView,
    TypVydajeCreateView,
    TypVydajeUpdateView,
    TypVydajeDeleteView,
)

urlpatterns = [
    path('', landing, name='landing'),
    path('prehled/', home, name='home'),
    path('vydaje/', VydajListView.as_view(), name='seznam_vydaju'),
    path('vydaje/pridat/', VydajCreateView.as_view(), name='pridat_vydaj'),
    path('vydaje/<int:pk>/upravit/', VydajUpdateView.as_view(), name='upravit_vydaj'),
    path('vydaje/<int:pk>/smazat/', VydajDeleteView.as_view(), name='smazat_vydaj'),
    path('vydaje/export/', export_vydaje_csv, name='export_vydaje_csv'),
    path('auta/', AutoListView.as_view(), name='seznam_aut'),
    path('auta/<int:pk>/', auto_detail, name='detail_auta'),
    path('auta/pridat/', AutoCreateView.as_view(), name='pridat_auto'),
    path('auta/<int:pk>/upravit/', AutoUpdateView.as_view(), name='upravit_auto'),
    path('auta/<int:pk>/smazat/', AutoDeleteView.as_view(), name='smazat_auto'),
    path('typy/', TypVydajeListView.as_view(), name='seznam_typu'),
    path('typy/pridat/', TypVydajeCreateView.as_view(), name='pridat_typ'),
    path('typy/<int:pk>/upravit/', TypVydajeUpdateView.as_view(), name='upravit_typ'),
    path('typy/<int:pk>/smazat/', TypVydajeDeleteView.as_view(), name='smazat_typ'),
    path('registrace/', registrace, name='registrace'),  # Přidání URL pro registraci
    path('prihlaseni/', prihlaseni, name='prihlaseni'),
    path('odhlasit/', odhlaseni, name='odhlaseni'),
]
